import {startQ1DBlankCase,calculateQ1DUserCase,runQ1DScenario,q1DAcceptanceCases} from '../../q1d/q1d-product-integration.js';
import {validateQ1DUserCase} from '../../q1d/q1d-canonical-input-bridge.js';
import {Q1D_ASSUMPTION_PACK} from '../../q1d/q1d-assumption-pack.js';
import {buildCandidate1Presentation} from '../candidate1-presentation.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS',maximumFractionDigits:0});
const money=v=>typeof v==='number'&&Number.isFinite(v)?fmt.format(v):'לא זמין';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateHe=d=>d?new Intl.DateTimeFormat('he-IL',{year:'numeric',month:'short',day:'numeric'}).format(new Date(`${d}T00:00:00Z`)):'מועד לא זמין';
const state={step:1,product:null,lastResult:null,lastPresentation:null,authorityProfileId:'F8_BETA_AUTHORITY_GENERAL_V1',caseId:null,stale:false,scenarioSeq:0};
window.__CANDIDATE1_BROWSER_ERRORS=[];
addEventListener('error',e=>window.__CANDIDATE1_BROWSER_ERRORS.push(String(e.error?.stack||e.message||e)));
addEventListener('unhandledrejection',e=>window.__CANDIDATE1_BROWSER_ERRORS.push(String(e.reason?.stack||e.reason||e)));

function systemCaseId(){return `C1-${Date.now().toString(36).toUpperCase()}`}
function n(id){const v=$(`#${id}`).value;return v===''?null:Number(v)}
function rawCase(){
  const spouse=$('#spouseRelevant').checked,rot=$('#rotationEnabled').checked;
  return {
    schemaVersion:'F8_BETA_USER_CASE_V1',caseId:state.caseId,asOfDate:$('#asOfDate')?.value||'2026-01-01',currency:'ILS',
    member:{age:n('memberAge'),sex:$('#memberSex').value},
    spouse:spouse?{relevant:true,age:n('spouseAge'),sex:$('#spouseSex').value}:{relevant:false},
    planningSource:{assetType:'SAVINGS_POLICY',balance:n('balance'),basisNominal:n('basisNominal'),basisIndexed:n('basisIndexed'),annualFee:n('annualFee'),providerRef:null,productRef:null,contractRef:null},
    service:{requiredNetMonthly:n('requiredNetMonthly')},
    rotationContract:rot?{enabled:true,providerRef:null,contractRef:$('#rotationContractRef').value.trim(),pensionFundCapital:n('pensionFundCapital'),annuityFactor:n('rotationAnnuityFactor'),commencementAge:n('commencementAge'),memberMonthlyGross:n('memberMonthlyGross'),replaceableMonthlyGross:n('replaceableMonthlyGross'),spouseShare:n('rotationSpouseShare'),guaranteeShare:n('rotationGuaranteeShare')}:{enabled:false},
    permissions:{qualifying:$('#qualifyingPermission').checked?'ALLOW':'DISALLOW',optionalAnnuitization:$('#optionalPermission').checked?'ALLOW':'DISALLOW'}
  };
}
function showStep(step){state.step=Math.max(1,Math.min(4,step));$$('.step-panel').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===state.step));$$('[data-step-nav]').forEach(x=>x.classList.toggle('active',Number(x.dataset.stepNav)===state.step));$('#backButton').classList.toggle('hidden',state.step===1);$('#nextButton').classList.toggle('hidden',state.step===4);$('#calculateButton').classList.toggle('hidden',state.step!==4);if(state.step===4)refreshReview()}
function issueKey(path){const p=String(path??'');return p.split('.').pop()?.replace(/\[.*$/,'')??''}
function clearErrors(){$$('label em').forEach(x=>x.textContent='')}
function validation(){const v=validateQ1DUserCase(rawCase(),{authorityProfileId:state.authorityProfileId});clearErrors();for(const i of v.issues??[]){const k=issueKey(i.path??i.field??'');const el=document.querySelector(`[data-error-for="${CSS.escape(k)}"]`);if(el&&!el.textContent)el.textContent=i.message}return v}
function reviewLine(label,value){return `<div class="review-line"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`}
function refreshReview(){const r=rawCase(),v=validation();$('#reviewFacts').innerHTML=`<div class="review-list">${reviewLine('מועד נתונים',r.asOfDate||'חסר')}${reviewLine('עמית',r.member.age==null?'חסר':`גיל ${r.member.age} · ${r.member.sex==='male'?'זכר':'נקבה'}`)}${reviewLine('בן/בת זוג',r.spouse.relevant?`גיל ${r.spouse.age??'חסר'}`:'לא רלוונטי')}${reviewLine('הון לתכנון',r.planningSource.balance==null?'חסר':money(r.planningSource.balance))}${reviewLine('מוצר','פוליסת חיסכון')}${reviewLine('צורך חודשי',r.service.requiredNetMonthly==null?'חסר':money(r.service.requiredNetMonthly))}${reviewLine('חוזה קצבה/רוטציה',r.rotationContract.enabled?'קיים חוזה נתמך':'לא קיים')}${reviewLine('בדיקת רובד מזכה',r.permissions.qualifying==='ALLOW'?'מותר למנוע לבדוק':'לא')}${reviewLine('בדיקת קצבה אופציונלית',r.permissions.optionalAnnuitization==='ALLOW'?'מותר למנוע לבדוק':'לא')}</div>`;
  $('#reviewAuthority').innerHTML=`<div class="review-list">${reviewLine('חבילת הנחות',`${Q1D_ASSUMPTION_PACK.id} · ${Q1D_ASSUMPTION_PACK.version}`)}${reviewLine('מטבע','ILS')}${reviewLine('מודל פטירה','נקשר downstream על ידי סמכות Beta')}${reviewLine('יכולת הפקדה לרובד המזכה','נקשרת downstream; אינה מוזנת בטופס')}${reviewLine('חלופות קצבה זמינות','נקשרות downstream; המנוע בוחר אפשרות')}</div>`;
  const box=$('#validationSummary');box.className=`validation-summary ${v.valid?'ok':'error'}`;box.innerHTML=v.valid?'<strong>הנתונים תקינים לחישוב ב־Beta.</strong>':'<strong>לא ניתן לחשב עדיין.</strong><ul>'+v.issues.map(i=>`<li>${esc(i.message)}</li>`).join('')+'</ul>';
}
function invalidatePlan(){if(!state.product)return;state.stale=true;state.product=null;state.lastResult=null;state.lastPresentation=null;$('#staleNotice').classList.remove('hidden');$('#resultsScreen').classList.remove('active');$('#editCaseTop').classList.add('hidden')}
function showIntake(step=1){$('#resultsScreen').classList.remove('active');$('#intakeScreen').classList.add('active');showStep(step)}
function showResults(){ $('#intakeScreen').classList.remove('active');$('#resultsScreen').classList.add('active');$('#editCaseTop').classList.remove('hidden') }
function planStrategyHtml(p){return p.recommendation.strategy.length?p.recommendation.strategy.map(x=>`<div class="strategy-item"><span>${esc(x.label)}</span><strong>${money(x.amount)}</strong></div>`).join(''):'<div class="status-text">לא נבחר רכיב פעולה נוסף.</div>'}
function renderRecommendation(p){$('#recommendationRoot').innerHTML=`<article class="result-card"><div class="result-intro"><div><span class="pill">המלצה</span><h2>התוכנית שנבחרה על ידי המנוע</h2></div></div><div class="recommend-grid"><div class="metric planned"><span>עם תכנון</span><strong>${money(p.recommendation.expected.planned)}</strong><small>ערך צפוי לבחירת התוכנית</small></div><div class="metric"><span>ללא תכנון</span><strong>${money(p.recommendation.expected.baseline)}</strong><small>חלופת בסיס צפויה</small></div><div class="metric delta"><span>הפער למשפחה</span><strong>${money(p.recommendation.expected.delta)}</strong><small>פער צפוי</small></div></div><div class="why-card"><h3>למה זו התוכנית שנבחרה?</h3><ul>${p.recommendation.why.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="strategy-grid">${planStrategyHtml(p)}</div><div class="plan-distinction">${esc(p.recommendation.distinction)}</div></article>`}
function actionHtml(a,i){return `<div class="action-row" data-action-id="${esc(a.actionId)}"><span class="action-no">${i+1}</span><div class="action-copy"><strong>${esc(a.what)}</strong><p>${esc(a.source)} → ${esc(a.destination)}</p><small>${a.date?dateHe(a.date):'המועד אינו זמין'} · ${esc(a.then??'')}</small>${a.stopCondition?`<small>תנאי עצירה: ${esc(a.stopCondition)}</small>`:''}</div><div class="action-amount">${money(a.amount)}</div></div>`}
function renderActionPlan(p){let idx=0;$('#actionPlanRoot').innerHTML=`<article class="section-card"><span class="pill">תוכנית ביצוע</span><h2>מה עושים בפועל</h2><div class="action-groups">${p.actionGroups.map(g=>`<section class="action-group"><h3>${esc(g.label)}</h3><div class="action-list">${g.actions.map(a=>actionHtml(a,idx++)).join('')}</div></section>`).join('')||'<div class="status-text">לא נדרשת פעולה בתוכנית זו.</div>'}</div></article>`}
function movieEvent(e){return `<div class="movie-event ${e.actionId==='SCENARIO_MEMBER_DEATH'?'death':''}"><time>${esc(e.date?dateHe(e.date):e.year??'')}</time><strong>${esc(e.what)}</strong>${e.amount!=null?`<span>${money(e.amount)}</span>`:''}${e.source?`<span>${esc(e.source)} → ${esc(e.destination)}</span>`:''}</div>`}
function rowStatus(v){return typeof v==='number'&&Number.isFinite(v)?money(v):'לא זמין בנתונים הקנוניים'}
function yearlyRows(p){if(!p.movie.rows.length)return '<div class="status-text">אין כרגע פירוט שנתי קנוני לתרחיש.</div>';const trs=p.movie.rows.map(r=>`<tr><td>${esc(r.calendarYear??'—')}</td><td>${r.projectionStatus==='ACTION_ONLY'?'פעולה מתוכננת; נתוני מאזן לא זמינים לשנה זו.':'נתוני הקרנה זמינים'}</td><td>${rowStatus(r.taxTotal)}</td><td>${rowStatus(r.NIHealthTotal)}</td><td>${rowStatus(r.feesTotal)}</td><td>${esc((r.actionIds??[]).length?`${r.actionIds.length} פעולה/ות`:'—')}</td></tr>`).join('');const cards=p.movie.rows.map(r=>`<div class="year-card"><strong>${esc(r.calendarYear??'—')}</strong><span>${r.projectionStatus==='ACTION_ONLY'?'פעולה מתוכננת; נתוני מאזן לא זמינים.':'שורת הקרנה קנונית'}</span><span>מס: ${rowStatus(r.taxTotal)}</span><span>NI/בריאות: ${rowStatus(r.NIHealthTotal)}</span></div>`).join('');return `<details class="yearly-details"><summary>פירוט שנתי</summary><div class="yearly-table-wrap"><table class="yearly-table"><thead><tr><th>שנה</th><th>מצב נתונים</th><th>מס</th><th>NI/בריאות</th><th>עלויות</th><th>אירועים</th></tr></thead><tbody>${trs}</tbody></table></div><div class="mobile-year-cards">${cards}</div></details>`}
function cellText(cell){if(!cell)return '<span class="status-text">לא זמין</span>';if(cell.amount!=null)return `<strong>${money(cell.amount)}</strong>`;const map={MISSING:'המידע לא קיים בנתונים הקנוניים',UNKNOWN:'לא ניתן לקבוע מהמידע הקיים',UNVERIFIED:'דורש אימות',BLOCKED:'לא ניתן לחשב כרגע',NOT_APPLICABLE:'לא רלוונטי'};return `<span class="status-text">${esc(map[cell.status]??'לא זמין')}</span>`}
function familyHtml(p){if(p.family.status==='ORDERING_UNRESOLVED')return `<div class="unresolved"><strong>לא ניתן לקבוע את סדר האירועים ביום הזה.</strong><br>${esc(p.family.message)}</div>`;if(p.family.status!=='AVAILABLE')return `<div class="status-text">${esc(p.family.message)}</div>`;const c=p.family.contract;const contract=c?`<div class="family-contract"><div><span>שיעור קצבת שאירים בחוזה</span><strong>${c.survivorPercent==null?'לא זמין':`${Math.round(c.survivorPercent*100)}%`}</strong></div><div><span>תקופת הבטחה</span><strong>${c.guaranteeMonths==null?'לא זמין':`${c.guaranteeMonths} חודשים`}</strong></div><p>מקור התשלום: זכות הקצבה שנבחרה. לאחר תקופת ההבטחה התשלום נקבע לפי זכות השאירים החוזית. אם בן/בת הזוג נפטר/ת קודם, אותה תוכנית נשארת קפואה והמשך התשלומים נקבע לפי תנאי ההבטחה בחוזה.</p></div>`:'';return `${contract}<div class="family-story">${p.family.steps.map(s=>`<div class="family-step"><h3>${esc(s.title)}</h3><div>${s.cell?cellText(s.cell):''}${s.text?`<p>${esc(s.text)}</p>`:''}</div></div>`).join('')}</div>`}
function professionalHtml(p){const pr=p.professional;return `<details class="professional"><summary>פירוט מקצועי</summary><div class="prof-grid"><div class="prof-card"><strong>חבילת הנחות</strong>${esc(pr.assumptionPackId??'—')}<br>${esc(pr.assumptionPackVersion??'—')}</div><div class="prof-card"><strong>מצב אימות</strong>${pr.productionReady?'מאומת לשימוש Production':'Professional Simulation Beta — נדרש אימות לפני שימוש מעשי'}</div><div class="prof-card"><strong>ראיות חוזיות</strong>${pr.rightsCount} זכויות · ${pr.capacityEvidenceCount} קבוצות קיבולת</div><div class="prof-card"><strong>עקביות תצוגה</strong>${esc(pr.reconciliation??'לא זמין')}</div>${pr.warnings.length?`<div class="prof-card"><strong>אזהרות</strong>${pr.warnings.map(x=>esc(x)).join('<br>')}</div>`:''}${pr.blockedReasons.length?`<div class="prof-card"><strong>חסמי Production</strong>${pr.blockedReasons.map(x=>esc(x)).join('<br>')}</div>`:''}</div></details>`}
function renderDynamic(result,p){const unresolved=p.orderingUnresolved;const scenarioValue=p.recommendation.scenario?.planned;const spouseRelevant=rawCase().spouse.relevant;return `<article class="section-card"><span class="pill">Money Movie</span><h2>מה קורה לכסף לאורך הדרך?</h2><div class="movie-events">${p.movie.events.map(movieEvent).join('')||'<div class="status-text">אין אירועים קנוניים להצגה.</div>'}</div>${yearlyRows(p)}</article><article class="section-card"><div class="explore-grid"><section class="whatif-card"><h2>אותה תוכנית — תרחיש אחר</h2><span class="same-plan">התוכנית נשארת קפואה</span><label><span>מועד פטירת העמית</span><input id="memberDeathDate" type="date" value="${esc(result.scenario.memberDate??'2030-04-15')}"></label>${spouseRelevant?`<label><span>מועד פטירת בן/בת הזוג</span><input id="spouseDeathDate" type="date" value="${esc(result.scenario.spouseDate??'2031-06-15')}"></label>`:''}<div class="whatif-status" id="scenarioStatus">שינוי תאריך מריץ replay על אותה תוכנית, ללא אופטימיזציה חדשה.</div>${unresolved?`<div class="unresolved">${esc(unresolved.message)}</div>`:`<div class="scenario-value"><span>ערך למשפחה בתרחיש הנוכחי</span><strong>${money(scenarioValue)}</strong><small>זהו What-if, לא Expected Plan Value חדש.</small></div>`}</section><section><span class="pill">תוצאת המשפחה</span><h2>מה המשפחה מקבלת?</h2>${familyHtml(p)}</section></div>${professionalHtml(p)}</article>`}
function commitDynamic(result){const p=buildCandidate1Presentation(state.product,result);const root=$('#dynamicRoot');const template=document.createElement('template');template.innerHTML=renderDynamic(result,p);root.replaceChildren(template.content.cloneNode(true));state.lastResult=result;state.lastPresentation=p;wireScenarioControls();window.__CANDIDATE1_STATE={status:result.status,planId:state.product.planProjection.planId,planIdentityHash:state.product.planProjection.identityHash,optimizerCalls:result.optimizerCalls,presentation:p,canonicalCaseHash:state.product.canonicalCaseHash}}
function scenarioSpec(){return {id:`candidate1:${++state.scenarioSeq}`,memberDeathDate:$('#memberDeathDate')?.value||'2030-04-15',spouseDeathDate:$('#spouseDeathDate')?.value||null}}
function runScenarioAtomic(){if(!state.product)return;const root=$('#dynamicRoot');root.classList.add('loading-mask');const status=$('#scenarioStatus');if(status)status.innerHTML='<span class="spinner-dot"></span> מחשב תרחיש…';const spec=scenarioSpec();setTimeout(()=>{try{const result=runQ1DScenario(state.product,spec);commitDynamic(result)}catch(e){window.__CANDIDATE1_BROWSER_ERRORS.push(String(e.stack||e));if(status)status.textContent='לא ניתן לחשב את התרחיש.'}finally{root.classList.remove('loading-mask')}},0)}
function wireScenarioControls(){const m=$('#memberDeathDate'),s=$('#spouseDeathDate');if(m)m.addEventListener('change',runScenarioAtomic);if(s)s.addEventListener('change',runScenarioAtomic)}
function calculate(){const v=validation();refreshReview();if(!v.valid){$('#calcStatus').textContent='יש להשלים את השדות המסומנים לפני החישוב.';return}$('#calcStatus').innerHTML='<span class="spinner-dot"></span> מחשב תוכנית…';$('#calculateButton').disabled=true;setTimeout(()=>{try{const product=calculateQ1DUserCase(rawCase(),{authorityProfileId:state.authorityProfileId});if(product.status!=='READY'){throw new Error('הקלט לא הגיע למצב READY')}state.product=product;state.stale=false;$('#staleNotice').classList.add('hidden');const initial=runQ1DScenario(product,{id:'candidate1:initial',memberDeathDate:'2030-04-15',spouseDeathDate:rawCase().spouse.relevant?'2031-06-15':null});const p=buildCandidate1Presentation(product,initial);renderRecommendation(p);renderActionPlan(p);commitDynamic(initial);showResults();$('#calcStatus').textContent=''}catch(e){window.__CANDIDATE1_BROWSER_ERRORS.push(String(e.stack||e));$('#calcStatus').textContent='לא ניתן להשלים את החישוב. בדקו את הנתונים וההרשאות.'}finally{$('#calculateButton').disabled=false}},0)}
function reset(){state.product=null;state.lastResult=null;state.lastPresentation=null;state.stale=false;state.scenarioSeq=0;state.authorityProfileId='F8_BETA_AUTHORITY_GENERAL_V1';state.caseId=systemCaseId();const b=startQ1DBlankCase();$('#asOfDate').value=b.asOfDate||'2026-01-01';
  $('#memberAge').value='';$('#memberSex').value='male';$('#spouseRelevant').checked=false;$('#spouseAge').value='';$('#spouseSex').value='female';$$('.spouse-field').forEach(x=>x.classList.add('hidden'));for(const id of ['balance','annualFee','basisNominal','basisIndexed','requiredNetMonthly','rotationContractRef','pensionFundCapital','rotationAnnuityFactor','commencementAge','memberMonthlyGross','replaceableMonthlyGross','rotationSpouseShare','rotationGuaranteeShare'])$(`#${id}`).value='';$('#rotationEnabled').checked=false;$('#rotationFields').classList.add('hidden');$('#qualifyingPermission').checked=false;$('#optionalPermission').checked=false;$('#validationSummary').innerHTML='';$('#calcStatus').textContent='';$('#staleNotice').classList.add('hidden');$('#recommendationRoot').innerHTML='';$('#actionPlanRoot').innerHTML='';$('#dynamicRoot').innerHTML='';$('#editCaseTop').classList.add('hidden');showIntake(1);window.__CANDIDATE1_STATE={status:'EMPTY',planId:null,optimizerCalls:0}}
function fillPreset(entry){const r=entry.rawInput;state.authorityProfileId=entry.authorityProfileId;state.caseId=r.caseId;$('#asOfDate').value=r.asOfDate;$('#memberAge').value=r.member.age;$('#memberSex').value=r.member.sex;$('#spouseRelevant').checked=r.spouse.relevant;$$('.spouse-field').forEach(x=>x.classList.toggle('hidden',!r.spouse.relevant));if(r.spouse.relevant){$('#spouseAge').value=r.spouse.age;$('#spouseSex').value=r.spouse.sex}$('#balance').value=r.planningSource.balance;$('#annualFee').value=r.planningSource.annualFee;$('#basisNominal').value=r.planningSource.basisNominal;$('#basisIndexed').value=r.planningSource.basisIndexed;$('#requiredNetMonthly').value=r.service.requiredNetMonthly;$('#rotationEnabled').checked=r.rotationContract.enabled;$('#rotationFields').classList.toggle('hidden',!r.rotationContract.enabled);if(r.rotationContract.enabled){$('#rotationContractRef').value=r.rotationContract.contractRef;$('#pensionFundCapital').value=r.rotationContract.pensionFundCapital;$('#rotationAnnuityFactor').value=r.rotationContract.annuityFactor;$('#commencementAge').value=r.rotationContract.commencementAge;$('#memberMonthlyGross').value=r.rotationContract.memberMonthlyGross;$('#replaceableMonthlyGross').value=r.rotationContract.replaceableMonthlyGross;$('#rotationSpouseShare').value=r.rotationContract.spouseShare;$('#rotationGuaranteeShare').value=r.rotationContract.guaranteeShare}$('#qualifyingPermission').checked=r.permissions.qualifying==='ALLOW';$('#optionalPermission').checked=r.permissions.optionalAnnuitization==='ALLOW';showStep(4);refreshReview()}

$('#spouseRelevant').addEventListener('change',()=>{$$('.spouse-field').forEach(x=>x.classList.toggle('hidden',!$('#spouseRelevant').checked));if(state.product)invalidatePlan()});$('#rotationEnabled').addEventListener('change',()=>{$('#rotationFields').classList.toggle('hidden',!$('#rotationEnabled').checked);if(state.product)invalidatePlan()});
$$('#intakeScreen input,#intakeScreen select').forEach(el=>el.addEventListener('change',()=>{if(state.product)invalidatePlan();if(state.step===4)refreshReview()}));
$('#backButton').addEventListener('click',()=>showStep(state.step-1));$('#nextButton').addEventListener('click',()=>showStep(state.step+1));$$('[data-step-nav]').forEach(b=>b.addEventListener('click',()=>showStep(Number(b.dataset.stepNav))));$('#calculateButton').addEventListener('click',calculate);$('#newCaseTop').addEventListener('click',reset);$('#editCaseTop').addEventListener('click',()=>showIntake(4));$('#editCaseButton').addEventListener('click',()=>showIntake(4));
if(new URLSearchParams(location.search).get('qa')==='1'){$('#qaPanel').classList.remove('hidden');$$('[data-preset]').forEach(b=>b.addEventListener('click',()=>fillPreset(q1DAcceptanceCases()[b.dataset.preset])))}
reset();
window.CANDIDATE1QA=Object.freeze({fillPreset,calculate,validate:validation,runScenario:runScenarioAtomic,getState:()=>window.__CANDIDATE1_STATE,getProduct:()=>state.product,getResult:()=>state.lastResult,errors:()=>[...window.__CANDIDATE1_BROWSER_ERRORS],presets:q1DAcceptanceCases(),newCase:reset,showStep});
