import {assertCapitalProjectionV1,caseIdentity,DEFAULTS} from './c2b-contracts.js';
import {accumulate,nominalFromReal,qualifyingInitial,amountAtTarget,realDisplay} from './c2b-economic-primitives.js';
import {evaluateCapitalBaseline} from './c2b-baseline.js';
const freeze=x=>{if(x&&typeof x==='object'&&!Object.isFrozen(x)){for(const v of Object.values(x))freeze(v);Object.freeze(x)}return x};
export function runCapitalPlanned(caseObj){const a=caseObj.assumptions,years=caseObj.targetWithdrawalAge-caseObj.currentAge,nominal=nominalFromReal(a.realReturn,a.inflation),policy=accumulate({deposit:caseObj.initialPlanningCapital,years,nominalReturn:nominal,inflation:a.inflation,fee:a.feePolicy,taxRate:a.policyTaxRate,taxBasisMode:'real'});const candidates=[{id:'CAPITAL:SAVINGS_POLICY',product:'SAVINGS_POLICY',netLumpSum:policy.net,gross:policy.gross,tax:policy.tax,requiredAnnuityCapital:0,feasible:true,reason:'SUPPORTED_POLICY'}];
  if(caseObj.targetWithdrawalAge>=60){const t=accumulate({deposit:caseObj.initialPlanningCapital,years,nominalReturn:nominal,inflation:a.inflation,fee:a.fee190,taxRate:a.t190TaxRate,taxBasisMode:'nominal'}),q0=qualifyingInitial({capital:caseObj.initialPlanningCapital,firstLayer:DEFAULTS.firstLayer,firstLayerAlreadySatisfied:caseObj.t190Facts.firstLayerAlreadySatisfied,firstLayerUsedAmount:caseObj.t190Facts.firstLayerUsedAmount}),qTarget=amountAtTarget({amount:q0,totalInitial:caseObj.initialPlanningCapital,totalGross:t.gross}),minAtTarget=caseObj.t190Facts.statutoryMinimumPensionMonthly*Math.pow(1+a.inflation,years),gap=Math.max(0,minAtTarget-caseObj.t190Facts.existingPensionAtTarget),gapCapital=gap*caseObj.contract.annuityFactor,required=Math.max(qTarget,gapCapital),feasible=required<=t.gross+1e-7;let net=0,tax=0,recognizedGross=0,recognizedBasis=0;if(feasible){recognizedGross=Math.max(0,t.gross-required);recognizedBasis=t.gross>0?caseObj.initialPlanningCapital*(recognizedGross/t.gross):0;tax=Math.max(0,recognizedGross-recognizedBasis)*a.t190TaxRate;net=recognizedGross-tax}candidates.push({id:'CAPITAL:T190',product:'T190',netLumpSum:net,gross:recognizedGross,tax,requiredAnnuityCapital:Math.min(required,t.gross),requiredAnnuityMonthly:caseObj.contract.annuityFactor>0?Math.min(required,t.gross)/caseObj.contract.annuityFactor:0,qualifyingCapital:qTarget,minimumPensionGapMonthly:gap,feasible,reason:feasible?'SUPPORTED_T190':'ANNUITY_CONSTRAINT_EXCEEDS_CAPITAL'})}
  const feasible=candidates.filter(x=>x.feasible),winner=[...feasible].sort((x,y)=>y.netLumpSum-x.netLumpSum||x.requiredAnnuityCapital-y.requiredAnnuityCapital)[0];return {objective:'MAX_NET_LUMP_SUM',optimizerCalls:1,candidates,winner,planId:`capital-plan:${caseIdentity(caseObj)}:${winner.id}`,value:winner.netLumpSum}}
export function projectCapitalV1(caseObj,{baselineType=caseObj.baselineType}={}){const planned=runCapitalPlanned(caseObj),baseline=evaluateCapitalBaseline(caseObj,baselineType),years=caseObj.targetWithdrawalAge-caseObj.currentAge,p={schema:'CapitalProjectionV1',caseId:caseIdentity(caseObj),baseline,planned:{value:planned.value,objective:planned.objective,planId:planned.planId,winner:planned.winner,candidates:planned.candidates,optimizerCalls:planned.optimizerCalls},winner:planned.winner,netLumpSumAtTargetAge:planned.value,requiredAnnuityConstraint:{capital:planned.winner.requiredAnnuityCapital||0,monthly:planned.winner.requiredAnnuityMonthly||0},comparisonEvidence:{baselineType,baselineValue:baseline.value,plannedValue:planned.value,benefit:planned.value-baseline.value,plannedIdentity:planned.planId},presentation:{nominal:{baseline:baseline.value,planned:planned.value},realToday:{baseline:realDisplay(baseline.value,caseObj.assumptions.inflation,years),planned:realDisplay(planned.value,caseObj.assumptions.inflation,years)}},warnings:planned.winner.feasible?[]:['NO_FEASIBLE_PLAN']};assertCapitalProjectionV1(p);return freeze(p)}
export function rebaselineCapitalProjection(caseObj,plannedProjection,baselineType){const baseline=evaluateCapitalBaseline(caseObj,baselineType),years=caseObj.targetWithdrawalAge-caseObj.currentAge;return freeze({...plannedProjection,baseline,comparisonEvidence:{...plannedProjection.comparisonEvidence,baselineType,baselineValue:baseline.value,plannedValue:plannedProjection.planned.value,benefit:plannedProjection.planned.value-baseline.value,plannedIdentity:plannedProjection.planned.planId},presentation:{nominal:{baseline:baseline.value,planned:plannedProjection.planned.value},realToday:{baseline:realDisplay(baseline.value,caseObj.assumptions.inflation,years),planned:realDisplay(plannedProjection.planned.value,caseObj.assumptions.inflation,years)}}})}
